### ISSUE TITLE
ci: node v16 unsupported engine

### ISSUE THREAD

**Issue by wandapeter** [jthegedus/awesome-list-template#12]
Hello,

Thank you for this template!
While testing i've found node v16 to be no longer supported by awesome-lint.

```
 Run npx -y awesome-lint readme.md
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'awesome-lint@1.0.0',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'execa@8.0.1',
npm WARN EBADENGINE   required: { node: '>=16.17' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'meow@12.1.1',
npm WARN EBADENGINE   required: { node: '>=16.10' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'human-signals@5.0.0',
npm WARN EBADENGINE   required: { node: '>=16.17.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'normalize-package-data@6.0.0',
npm WARN EBADENGINE   required: { node: '^16.14.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'hosted-git-info@7.0.1',
npm WARN EBADENGINE   required: { node: '^16.14.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'lru-cache@10.0.2',
npm WARN EBADENGINE   required: { node: '14 || >=16.14' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'json-parse-even-better-errors@3.0.0',
npm WARN EBADENGINE   required: { node: '^14.17.0 || ^16.13.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.5.0', npm: '7.19.1' }
npm WARN EBADENGINE }
file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/options.js:15
				filter: ([, flag]) => Object.hasOwn(flag, 'alias'),
				                             ^

TypeError: Object.hasOwn is not a function
    at filter (file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/options.js:15:34)
    at file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/options.js:42:58
    at Array.filter (<anonymous>)
    at validateOptions (file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/options.js:42:41)
    at buildOptions (file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/options.js:87:2)
    at meow (file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/meow/build/index.js:86:24)
    at file:///home/runner/.npm/_npx/b4a07bb0d9034d53/node_modules/awesome-lint/cli.js:21:13
Error: Process completed with exit code 1.
```

**Comment by jthegedus** [comment]
closed in #13 & #14
